#!/bin/bash
cd /opt
#java installation
wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
#start the java
rpm -ivh jdk-8u131-linux-x64.rpm
# install tomcat 
wget https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46-windows-x64.zip
# unzip the tomcat file
unzip apache-tomcat-9.0.46-windows-x64.zip
# rename the tomcat file
mv apache-tomcat-9.0.46 tomcat
# allow the permissions 700 to tomcat folder
chmod -R 700 tomcat
# goto inside tomcat directory
cd tomcat/bin
# start up the tomcat server
./startup.sh